# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 <LICENSE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

edition = "2024"
style_edition = "2021"
use_small_heuristics = "Max"
newline_style = "Unix"
